### ISSUE TITLE
Open sourcing the project?

### ISSUE THREAD

**Issue by louis-pre** [akhanubis/anu_twitch_chat_overlay#56]
Love the project, can't use Twitch without it.

My impression is that support has been slowing down, which makes sense for a personal project. 

I believe open sourcing the project so that others could share the burden of adapting it to Twitch's inevitable changes could be beneficial for both the creator and the users.

Would you be open to it?

**Comment by akhanubis** [comment]
It was supposed to be a tool for my friends so I coded it in a rush without considering good coding practices. Nevertheless, I dont have the time to provide much support nowadays, as you mentioned.

I'll push the code (which I''m not proud of lol) to this repo and rename it to anu_twitch_chat_overlay.

**Comment by louis-pre** [comment]
That's really good news! 

Thanks a lot for that, I've got a few private repos that I have never been made public for that exact reason so I understand the feeling haha 

I'm sure some people will be looking into improving it 👍  (me included)
